### ISSUE TITLE
Any README.md?

### ISSUE THREAD

**Issue by bubnov-mikhail** [PHPixie/Social#1]
It looks like ready to use lib, but without any examples.

**Comment by dracony** [comment]
I wrote a post on Habrahabr, but since it contained a grand total of 2(!!!!!) links, my account got suspended for a week, lol

Anyway, checkout the demo project:
https://github.com/phpixie/demo-socialauth

I'll translate the docs to English soon,a nd when my account gets unsuspended will post to habr =)
